name: bitcoin
services:
  main_app:
    cpu_shares: 10
    command:
      - /usr/bin/bitcoind
      - -printtoconsole
      - -server
      - -prune=550
      - -wallet=default
      - -zmqpubhashblock=tcp://0.0.0.0:7004
      - -rpcbind=0.0.0.0
      - -rpcport=9004
      - -rpcallowip=0.0.0.0/0
      - -port=8333
      - -rpcuser=pooluser
      - -rpcpassword=poolpassword
    container_name: btc
    deploy:
      resources:
        limits:
          memory: 67292020736
        reservations:
          devices: []
    image: theretromike/nodes:bitcoin
    labels:
      icon: https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Bitcoin.svg/1200px-Bitcoin.svg.png
    ports:
      - target: 9004
        published: "9004"
        protocol: tcp
      - target: 7004
        published: "7004"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/ZimaOS-HD/NodeData/btc
        target: /root/.bitcoin
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: Retro Mike
  category: RetroMike
  hostname: ""
  icon: https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Bitcoin.svg/1200px-Bitcoin.svg.png
  index: /
  is_uncontrolled: false
  port_map: "8888"
  scheme: http
  store_app_id: bitcoin
  title:
    custom: Bitcoin (BTC) Node
