name: bitcoin
services:
  main_app:
    command:
      - /usr/bin/bitcoind
      - -printtoconsole
      - -server
      - -prune=550
      - -wallet=default
      - -zmqpubhashblock=tcp://0.0.0.0:7004
      - -rpcbind=0.0.0.0
      - -rpcport=9004
      - -rpcallowip=0.0.0.0/0
      - -port=8333
      - -rpcuser=pooluser
      - -rpcpassword=poolpassword
    container_name: btc
    image: theretromike/nodes:bitcoin
    labels:
      icon: https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Bitcoin.svg/1200px-Bitcoin.svg.png
    ports:
      - target: 9004
        published: "9004"
        protocol: tcp
      - target: 7004
        published: "7004"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/ZimaOS-HD/NodeData/btc
        target: /root/.bitcoin
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Bitcoin Cryptocurrency Node. Can be used in conjunction with Miningcore Apps to solo mine.
  tagline:
    en_us: Bitcoin Cryptocurrency Node.
  developer: Retro Mike
  author: Retro Mike
  icon: https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Bitcoin.svg/1200px-Bitcoin.svg.png
  thumbnail: ""
  title:
    en_us: Bitcoin (BTC) Node
  category: RetroMike
  port_map: "8888"