name: retro-mike-bitcoin
services:
  app:
    container_name: btc
    image: theretromike/nodes:bitcoin
    restart: always
    volumes:
      - /media/ZimaOS-HD/btc:/root/.bitcoin
    ports:
      - "7004:7004"
      - "9004:9004"
      - "8333:8333"
    command: "/usr/bin/bitcoin -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7004 -rpcbind=0.0.0.0 -rpcport=9004 -rpcallowip=0.0.0.0/0 -port=8333 -rpcuser=pooluser -rpcpassword=poolpassword"
    x-casaos:
      volumes:
        - container: /root/.bitcoin
          description:
            en_us: 'Container Path: /root/.bitcoin'
      ports:
        - container: "7004"
          description:
            en_us: 'Container Port: 7004'
        - container: "9004"
          description:
            en_us: 'Container Port: 9004'
        - container: "8333"
          description:
            en_us: 'Container Port: 8333'
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Bitcoin Cryptocurrency Node. Can be used in conjunction with Miningcore Apps to solo mine.
  tagline:
    en_us: Bitcoin Cryptocurrency Node.
  developer: Retro Mike
  author: Retro Mike
  icon: https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Bitcoin.svg/1200px-Bitcoin.svg.png
  thumbnail: ""
  title:
    en_us: Bitcoin (BTC) Node
  category: RetroMike
  port_map: "8888"
