name: miningcore_legacy
services:
  app:
    container_name: miningcore_legacy
    image: theretromike/miningcore:legacy
    restart: always
    volumes:
      - /media/ZimaOS-HD/miningcore_legacy/coins.json:/app/build/coins.json
      - /media/ZimaOS-HD/miningcore_legacy/config.json:/app/config.json
      - /media/ZimaOS-HD/vtc:/.vertcoin
    ports:
      - "4001:4001"
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Miningcore Mining Pool App. Legacy version retained for Monero support.
  tagline:
    en_us: Miningcore Mining Pool App.
  developer: Retro Mike
  author: Retro Mike
  icon: https://raw.githubusercontent.com/oliverw/miningcore/master/logo.png
  thumbnail: ""
  title:
    en_us: Miningcore (Legacy)
  category: RetroMike
  port_map: "8888"
