name: retro-mike-bitcoin-cash
services:
  app:
    container_name: bch
    image: theretromike/nodes:bitcoincash
    restart: always
    volumes:
      # Mounting docker.sock to allow docker management via the container
      - /media/ZimaOS-HD/NodeData/bch:/root/.bitcoin
    ports:
      - "7002:7002"
      - "9002:9002"
      - "8334:8334"
    command: "/usr/bin/bitcoind -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7002 -rpcbind=0.0.0.0 -rpcport=9002 -rpcallowip=0.0.0.0/0 -port=8334 -rpcuser=pooluser -rpcpassword=poolpassword"
    x-casaos:
      volumes:
        - container: /root/.bitcoin
          description:
            en_us: 'Container Path: /root/.bitcoin'
      ports:
        - container: "7002"
          description:
            en_us: 'Container Port: 7002'
        - container: "9002"
          description:
            en_us: 'Container Port: 9002'
        - container: "8334"
          description:
            en_us: 'Container Port: 8334'
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Bitcoin Cash Cryptocurrency Node. Can be used in conjunction with Miningcore Apps to solo mine.
  tagline:
    en_us: Bitcoin Cash Cryptocurrency Node.
  developer: Retro Mike
  author: Retro Mike
  icon: https://bitcoincash.org/img/green/bitcoin-cash-circle.svg
  thumbnail: ""
  # Title for the application
  title:
    en_us: Bitcoin Cash (BCH) Node
  category: RetroMike
  port_map: "8888"
