name: neurai
services:
  app:
    container_name: xna
    image: theretromike/nodes:neurai
    restart: always
    volumes:
      - /media/ZimaOS-HD/NodeData/xna:/root/.neurai
    ports:
      - "7011:7011"
      - "9011:9011"
    command:
      - /usr/bin/neuraid
      - -printtoconsole
      - -server
      - -prune=550
      - -wallet=default
      - -zmqpubhashblock=tcp://0.0.0.0:7011
      - -rpcbind=0.0.0.0
      - -rpcport=9011
      - -rpcallowip=0.0.0.0/0
      - -rpcuser=pooluser
      - -rpcpassword=poolpassword
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Neurai Cryptocurrency Node. Can be used in conjunction with Miningcore Apps to solo mine.
  tagline:
    en_us: Neurai Cryptocurrency Node.
  developer: Retro Mike
  author: Retro Mike
  icon: https://s2.coinmarketcap.com/static/img/coins/200x200/27195.png
  thumbnail: ""
  title:
    en_us: NeurAI (XNA) Node
  category: RetroMike
  port_map: "8888"
