name: miningcore
services:
  app:
    container_name: miningcore
    image: theretromike/miningcore:latest
    restart: always
    volumes:
      - /media/ZimaOS-HD/miningcore/coins.json:/app/build/coins.json
      - /media/ZimaOS-HD/miningcore/config.json:/app/config.json
      - /media/ZimaOS-HD/vtc:/.vertcoin
    ports:
      - "4000:4000"
      - "6001:6001"
      - "6002:6002"
      - "6003:6003"
      - "6004:6004"
      - "6005:6005"
      - "6006:6006"
      - "6007:6007"
      - "6008:6008"
      - "6009:6009"
      - "6010:6010"
      - "6011:6011"
      - "6012:6012"
      - "6013:6013"
      - "6014:6014"
      - "6015:6015"
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Miningcore Mining Pool App.
  tagline:
    en_us: Miningcore Mining Pool App.
  developer: Retro Mike
  author: Retro Mike
  icon: https://raw.githubusercontent.com/oliverw/miningcore/master/logo.png
  thumbnail: ""
  title:
    en_us: Miningcore
  category: RetroMike
  port_map: "8888"
