name: miningcore
services:
  app:
    container_name: miningcore
    image: theretromike/miningcore:latest
    restart: always
    volumes:
      - /media/ZimaOS-HD/miningcore/coins.json:/app/build/coins.json
      - /media/ZimaOS-HD/miningcore/config.json:/app/config.json
      - /media/ZimaOS-HD/vtc:/.vertcoin
    ports:
      - "4000:4000"
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Miningcore Mining Pool App.
  tagline:
    en_us: Miningcore Mining Pool App.
  developer: Retro Mike
  author: Retro Mike
  icon: https://raw.githubusercontent.com/oliverw/miningcore/master/logo.png
  thumbnail: ""
  title:
    en_us: Miningcore
  category: RetroMike
  port_map: "8888"
