name: monero
services:
  main_app:
    cpu_shares: 10
    command:
      - /usr/local/bin/monerod
      - --non-interactive
      - --confirm-external-bind
      - --out-peers=32
      - --p2p-bind-ip=0.0.0.0
      - --p2p-bind-port=18080
      - --rpc-bind-ip=0.0.0.0
      - --rpc-bind-port=9009
      - --prune-blockchain
    container_name: xmr
    deploy:
      resources:
        limits:
          memory: 67292020736
        reservations:
          devices: []
    image: theretromike/nodes:monero
    labels:
      icon: https://cryptologos.cc/logos/monero-xmr-logo.png
    ports:
      - target: 9009
        published: "9009"
        protocol: tcp
      - target: 7009
        published: "7009"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/ZimaOS-HD/NodeData/xmr
        target: /root/.bitmonero
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: Retro Mike
  category: RetroMike
  hostname: ""
  icon: https://cryptologos.cc/logos/monero-xmr-logo.png
  index: /
  is_uncontrolled: false
  port_map: "8888"
  scheme: http
  store_app_id: monero
  title:
    custom: Monero (XMR) Node
