name: retro-mike-microvision
services:
  app:
    container_name: space
    image: theretromike/nodes:microvision
    restart: always
    volumes:
      - /media/ZimaOS-HD/mvc:/root/.mvc
    ports:
      - "7012:7012"
      - "9012:9012"
    command: "/usr/bin/mvcd -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7012 -rpcbind=0.0.0.0 -rpcport=9012 -rpcallowip=0.0.0.0/0 -rpcuser=pooluser -rpcpassword=poolpassword -addnode=45.153.35.150:31002 -addnode=45.153.35.150:8121 -addnode=47.242.24.63:55564"
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: MicroVisionChain Cryptocurrency Node. Can be used in conjunction with Miningcore Apps to solo mine.
  tagline:
    en_us: MicroVisionChain Cryptocurrency Node.
  developer: Retro Mike
  author: Retro Mike
  icon: https://s3.coinmarketcap.com/static-gravity/image/5985437d02b24be294ff83c572066343.jpg
  thumbnail: ""
  title:
    en_us: MicroVisionChain (SPACE) Node
  category: RetroMike
  port_map: "8888"