name: retro-mike-microvision
services:
  app:
    container_name: rvn
    image: theretromike/nodes:microvision
    restart: always
    volumes:
      - /media/ZimaOS-HD/mvc:/root/.mvc
    ports:
      - "7012:7012"
      - "9012:9012"
    command: "/usr/bin/mvcd -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7012 -rpcbind=0.0.0.0 -rpcport=9012 -rpcallowip=0.0.0.0/0 -rpcuser=pooluser -rpcpassword=poolpassword"
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: MicroVisionChain Cryptocurrency Node. Can be used in conjunction with Miningcore Apps to solo mine.
  tagline:
    en_us: MicroVisionChain Cryptocurrency Node.
  developer: Retro Mike
  author: Retro Mike
  icon: https://cryptologos.cc/logos/ravencoin-rvn-logo.png
  thumbnail: ""
  title:
    en_us: MicroVisionChain (SPACE) Node
  category: RetroMike
  port_map: "8888"
