name: monero
services:
  app:
    container_name: xmr
    image: theretromike/nodes:monero
    restart: always
    volumes:
      - /media/ZimaOS-HD/NodeData/xmrwallet:/root/.bitmonero
    ports:
      - "18082:18082"
    command:
      - /usr/local/bin/monero-wallet-rpc
      - --wallet-file=/root/.bitmonero/default
      - --password=poolpassword
      - --daemon-address=192.168.1.101:9009
      - --daemon-login=pooluser:poolpassword
      - --rpc-bind-port=18082
      - --rpc-bind-ip=0.0.0.0
      - --confirm-external-bind
      - --disable-rpc-login
      - --log-level=1
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Monero Cryptocurrency Wallet
  tagline:
    en_us: Monero Cryptocurrency Wallet
  developer: Retro Mike
  author: Retro Mike
  icon: https://cryptologos.cc/logos/monero-xmr-logo.png
  thumbnail: ""
  title:
    en_us: Monero (XMR) Wallet
  category: RetroMike
  port_map: "8888"
